### ISSUE TITLE
[Feedback] Cursor movement (dpa

### ISSUE THREAD

**Issue by 920-Text-Editor-User** [jecelyin/920-text-editor-v2#1523]
hemlocksolmes#gmail.com

Version: v2.17.8.30

Cursor movement (dpad left and right) sometimes highlights a character instead of moving the cursor.

Typing a word often doesn't move the cursor.

Trying to insert characters into an existing word doesn't work. Sometimes it will insert one character, highlight it, and then insert no more characters.

Backspace will often delete more than one character.

Auto capitalize doesn't always work.

Typing suggestions are not always shown.

All these bugs seem to be new.

Some user interface ideas:
Opening the keyboard covers the text where you placed the cursor. This is annoying. It would be nice if the text was automatically moved out of the way of the keyboard.

It would be nice to have a toggle in the side menu to toggle word wrap rather than having to go to settings to toggle it.

Exception Start ==============================

Exception End ==============================

Tag: JecLog
Msg: /storage/emulated/0/Documents/live at the hedge.txt (No such file or directory)
Stacktrace:
java.io.FileNotFoundException: /storage/emulated/0/Documents/live at the hedge.txt (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
	at com.jecelyin.editor.v2.io.FileWriter.doInBackground(FileWriter.java:85)
	at com.jecelyin.editor.v2.io.FileWriter.doInBackground(FileWriter.java:37)
	at android.os.AsyncTask$2.call(AsyncTask.java:306)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:244)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by eyedarts** [comment]
+1
