### ISSUE TITLE
寻求帮助 help

### ISSUE THREAD

**Issue by forwardhuan** [jecelyin/920-text-editor-v2#1692]
项目工程无法在android studio运行，有什么解决办法吗，希望收到你的回复，谢谢

The project engineering can't run in Android studio.Do you have solutions? I hope to receive your reply, thank you

**Comment by jecelyin** [comment]
可以运行的，自己研究下

**Comment by forwardhuan** [comment]
这个有什么需要注意的点吗






在 2017-11-27 10:06:04，"Jecelyin" <notifications@github.com> 写道：


可以运行的，自己研究下

**Comment by forwardhuan** [comment]
我尝试把那些key文件之类的给注释掉了，代码能编译，也能安装，但是运行的时候无法编辑内容，这部分实在什么地方控制的啊，能给个提示吗。
还有就是我一点击应用界面，它就会跳到错误提交页面
  java.lang.AbstractMethodError: abstract method "boolean android.view.inputmethod.InputConnection.isLauncherFocus(boolean)"
                at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:300)
                at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:79)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:135)
                at android.app.ActivityThread.main(ActivityThread.java:5254)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

谢谢了





在 2017-11-27 10:06:04，"Jecelyin" <notifications@github.com> 写道：


可以运行的，自己研究下

**Comment by jecelyin** [comment]
这个应该是系统层的错误，比较忙，你调试看看吧，自己找问题，可以提高技术能力 :-D

**Comment by forwardhuan** [comment]
恩，我再试试，谢啦

**Comment by forwardhuan** [comment]
我这边编译通过了，也能运行安装了，但是安装的920编辑器不显示编辑状态，找了好久也没确定原因，这个有可能是什么原因造成的啊，我编译的时候注掉了签名文件，还有一个获得github帐号密码的文件
