### ISSUE TITLE
920-text-editor-v2 开发问题求教

### ISSUE THREAD

**Issue by caoyongren** [jecelyin/920-text-editor-v2#1717]
Hello:
  首先, 先介绍一下：
  我们是一个openthos开源系统的开发人员，希望使用您开源的编辑器进行适配我们的系统成为我们系统中的编辑器，但是需要一些修改；下面是求教的事情:

个人clone code 后为了正常运行进行了一些配置:
1. 注释: //def GOOGLE_BILLING_KEY = properties.getProperty('GOOGLE_BILLING_KEY')
2. 替换了KEYSTORE_ALIAS  KEYSTORE_PASSWORD
3.  修改
    def GITHUB_USER = "caoyongren"
    def GITHUB_PWD = "*******"
4. 更改了gradle版本。

5. AppUtils.java中 verifySign修改－－> 注释检测直接 return true;

工具: studio 2.3.0 ubuntu 16.04系统

问题:
1. 在小米手机上，7.1系统 MIUI9.1
  可以正常运行，可以编辑,但是进行另存为出现奔溃下面图片为crash 提示(null object) [(官方应用可以)]
  ![crash点击看图](https://github.com/openthos/systemui-analysis/blob/master/CYR/icon/Screenshot%20from%202017-12-05%2016-14-45.png)

2.  我们定制的开源系统则更是出现点击就奔溃(错误显示我们系统底层原因)，但是官方应用则正常。

所以，我们想请教一下  出现这些问题的原因或者一些解决的意见。(目前除了上面配置的修改，其他没有修改)
说的有点啰嗦，希望您能得到回复。

备注:(我们项目) https://github.com/openthos/openthos/wiki/Home-zh_CN

团队邮箱: bigandroid@googlegroups.com

Thanks.

**Comment by caoyongren** [comment]
hello:
这个,之前同事进行说过:
可以看出是系统的原因，但是官方应用则没问题！　求原因

  java.lang.AbstractMethodError: abstract method "boolean android.view.inputmethod.InputConnection.isLauncherFocus(boolean)"
                at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:300)
                at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:79)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:135)
                at android.app.ActivityThread.main(ActivityThread.java:5254)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)


thanks.

**Comment by jecelyin** [comment]
java.lang.AbstractMethodError: abstract method "boolean android.view.inputmethod.InputConnection.isLauncherFocus(boolean)"

这个问题我在其他应用也遇到过，暂时不知道什么回事，另外我最近在着手把chrome内核打包入920，以解决输入法相关的问题，不过时间不充裕，要多点时间才能搞定了。

**Comment by caoyongren** [comment]
Hello:

打扰一下：

  我们现在的问题可能更倾向于怎么在我们本地编译生成的app-release.apk和您官方发布的一样，
安装在什么版本系统上都不存在任何问题。
若是配置的原因或我们修改的不正确再或是我们本地需要添加什么第三方的东西，
希望您有时间可以给我们提供一些方法或建议。

Thanks.

**Comment by caoyongren** [comment]
Hello:

  我对我们编译生产的apk和您githup发布的apk进行了解压缩然后查看assets发现您发布的apk中含有
ace文件夹，我姑且猜测这是差异问题的起因，求教这个tools中ace中的文件是怎么调用的？？？(本人js没有接触过, 时间也紧张，求指点一下)

![点击看图](https://github.com/openthos/systemui-analysis/blob/master/CYR/icon/Screenshot%20from%202017-12-06%2014-59-54.png)

Thanks.

**Comment by jecelyin** [comment]
是的，这个是要
$ cd tools/assets/ace/
$ node ./Makefile.dryice.js
具体看目录下的Readme.md，现在920的内核用的是ace.

**Comment by caoyongren** [comment]
Hello:
报错:且没有找到module.js

matthew@masterman:ace$ node Makefile.dryice.js 
module.js:328
    throw err;
    ^

Error: Cannot find module 'architect-build/copy'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/media/matthew/Android-studio/920-text-editor-v2-master/tools/assets/ace/Makefile.dryice.js:34:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
matthew@masterman:ace$ 

![详情看图](https://github.com/openthos/systemui-analysis/blob/master/CYR/icon/Screenshot%20from%202017-12-06%2018-30-09.png)


Thanks.

**Comment by jecelyin** [comment]
npm install 了没

**Comment by caoyongren** [comment]
Hello:

安装了

matthew@masterman:~$ npm -version
3.5.2

Thanks

**Comment by caoyongren** [comment]
Hello:

　通过这个: [nodejs/issues](https://github.com/nodejs/help/issues/663)
我解决了问题，目前可以在我的小米手机上和官方发布的一样运行,
遗憾, 我们openthos系统上没有和官方发布的一样成功运行，
我正准备分析，如果还有问题　估计还会讨教您。

谢谢您的帮助。

Thanks.

**Comment by caoyongren** [comment]
Hello:

再请教一下:

１．
 如何在android studio中将ace编译进入apk.
该方法: node ./Makefile.dryice.js只是在build时进行了写入，
但是好像还是不完整，apk反编译里面还是没有ace（官方apk则有）.


２．应用启动，立即获得输入的焦点，code中大概什么的地方。

打扰了。。。。


Thanks.

**Comment by jecelyin** [comment]
1. build ace时会写入app下的assets，你build时看看output log
2. 很多人不喜欢这样，你可以在js里在editor初始化时editor.focus()

**Comment by caoyongren** [comment]
Hello:

  我们本地编译的apk经过测试，发现一个bug:
点击选择文件，内容显示为空，然后多点击导航path,　频繁出现卡死现象。

这种情况您了解吗？？

Thanks.

**Comment by jecelyin** [comment]
这个没遇到过，你试试是不是root导致的
